name: Run Windows RDP Container

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout (gerekli değil ama standart)
        uses: actions/checkout@v3

      - name: Install Docker Compose & Curl
        run: |
          sudo apt update
          sudo apt install docker-compose curl -y

      - name: Create win10.yml
        run: |
          mkdir -p Windows
          cd Windows
          cat <<EOF > win10.yml
          services:
            windows:
              image: dockurr/windows
              container_name: windows
              environment:
                VERSION: "10"
                USERNAME: "MASTER"
                PASSWORD: "admin@123"
                RAM_SIZE: "4G"
                CPU_CORES: "4"
                DISK_SIZE: "400G"
                DISK2_SIZE: "100G"
              devices:
                - /dev/kvm
                - /dev/net/tun
              cap_add:
                - NET_ADMIN
              ports:
                - "8006:8006"
                - "3389:3389/tcp"
                - "3389:3389/udp"
              stop_grace_period: 2m
          EOF

      - name: Run Docker Compose
        run: |
          cd Windows
          docker-compose -f win10.yml up -d

      - name: Download Cloudflared
        run: |
          ARCH="amd64"
          URL="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${ARCH}"
          curl -L "$URL" -o cloudflared
          chmod +x cloudflared

      - name: Start Cloudflared Tunnel
        run: |
          ./cloudflared tunnel --url http://localhost:8006 --no-autoupdate > cf_log.txt 2>&1 &
          echo "Cloudflare linki oluşturuluyor..."
          sleep 10
          cat cf_log.txt
          LINK=$(grep -o "https://.*\.trycloudflare\.com" cf_log.txt | head -n1)
          echo "RDP bağlantı linkin: $LINK"
          echo "$LINK" > link.txt

      - name: Upload Cloudflare RDP Link
        uses: actions/upload-artifact@v4
        with:
          name: cloudflare-rdp-link
          path: link.txt
          - name: Sleep for 6 hours to keep the tunnel alive
        run: |
          echo "RDP oturumu 6 saat açık kalacak. Uyu bakalım 😴"
          sleep 21600
